"""Continuous recording of PM5 readings in HDF5 format.

Structure of the resulting file:

    /power                  compound dataset, one row per sample
        fields: timestamp (f8), watts (f8), dbm (f8), range_code (i4),
                auto_range (bool), cal_factor_db (f8)
    root group attributes:
        instrument = "VDI Erickson PM5"
        sensor_serial (if provided)
        created_at (UNIX timestamp of file creation)
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Optional, Union

import h5py
import numpy as np

from .driver import PowerReading

DTYPE = np.dtype([
    ("timestamp", "f8"),
    ("watts", "f8"),
    ("dbm", "f8"),
    ("range_code", "i4"),
    ("auto_range", "bool"),
    ("cal_factor_db", "f8"),
])

DATASET_NAME = "power"
CHUNK_SIZE = 256  # HDF5 samples per chunk; also the write-buffer size


class Hdf5PowerLogger:
    """Writes PM5 power readings to an HDF5 file incrementally.

    Usage:
        with Hdf5PowerLogger("measurement.h5", sensor_serial="347VA") as logger:
            for reading in pm5.stream_power(poll_interval=1.0):
                logger.append(reading)
    """

    def __init__(
        self,
        path: Union[str, Path],
        sensor_serial: Optional[str] = None,
        mode: str = "a",
        flush_every: int = 1,
    ):
        self.path = Path(path)
        self.flush_every = max(1, flush_every)
        self._pending = 0
        self._file = h5py.File(self.path, mode)

        if DATASET_NAME not in self._file:
            ds = self._file.create_dataset(
                DATASET_NAME,
                shape=(0,),
                maxshape=(None,),
                dtype=DTYPE,
                chunks=(CHUNK_SIZE,),
            )
            self._file.attrs["instrument"] = "VDI Erickson PM5"
            self._file.attrs["created_at"] = time.time()
            if sensor_serial:
                self._file.attrs["sensor_serial"] = sensor_serial
        self._dataset = self._file[DATASET_NAME]

    def append(self, reading: PowerReading, timestamp: Optional[float] = None) -> None:
        """Appends a sample to the dataset. `timestamp` is a UNIX epoch value; if omitted, current time is used."""
        ts = timestamp if timestamp is not None else time.time()
        row = np.array(
            [(ts, reading.watts, reading.dbm, reading.range_code or -1, reading.auto_range, reading.cal_factor_db)],
            dtype=DTYPE,
        )
        n = self._dataset.shape[0]
        self._dataset.resize((n + 1,))
        self._dataset[n] = row[0]
        self._pending += 1
        if self._pending >= self.flush_every:
            self.flush()

    def flush(self) -> None:
        self._file.flush()
        self._pending = 0

    def close(self) -> None:
        self.flush()
        self._file.close()

    def __enter__(self) -> "Hdf5PowerLogger":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()

    def __len__(self) -> int:
        return self._dataset.shape[0]


def read_power_log(path: Union[str, Path]) -> np.ndarray:
    """Reads back a file generated by Hdf5PowerLogger as a structured array."""
    with h5py.File(path, "r") as f:
        return f[DATASET_NAME][:]
